services:
  kube-sentinel:
    build: .
    image: kube-sentinel:local
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT:-8080}
      #- HOST=${HOST}
      #- KUBE_SENTINEL_BASE=${KUBE_SENTINEL_BASE}
      #- JWT_SECRET=${JWT_SECRET}
      #- KUBE_SENTINEL_ENCRYPT_KEY=${KUBE_SENTINEL_ENCRYPT_KEY}
      #- KUBE_SENTINEL_USERNAME=${KUBE_SENTINEL_USERNAME:-admin}
      #- KUBE_SENTINEL_PASSWORD=${KUBE_SENTINEL_PASSWORD:-admin}
      - DB_TYPE=${DB_TYPE}
      - DB_DSN=${DB_DSN}
      #- KUBECONFIG=${KUBECONFIG}
      #- NODE_TERMINAL_IMAGE=${NODE_TERMINAL_IMAGE}
      - GITLAB_HOSTS=${GITLAB_HOSTS}
      - INSECURE_SKIP_VERIFY=${INSECURE_SKIP_VERIFY}
      #- DISABLE_GZIP=${DISABLE_GZIP}
      #- DISABLE_VERSION_CHECK=${DISABLE_VERSION_CHECK}
