{{- if and (eq .Values.db.type "sqlite") .Values.db.sqlite.persistence.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kube-sentinel.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-sentinel.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.db.sqlite.persistence.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.db.sqlite.persistence.pvc.size }}
  {{- if .Values.db.sqlite.persistence.pvc.storageClass }}
  storageClassName: {{ .Values.db.sqlite.persistence.pvc.storageClass }}
  {{- end }}
{{- end }}
