{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-sentinel.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-sentinel.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
  CLOUD_SENTINEL_K8S_ENCRYPT_KEY: {{ .Values.encryptKey | b64enc | quote }}
  {{- if ne .Values.db.type "sqlite" }}
  DB_TYPE: {{ .Values.db.type | b64enc | quote }}
  DB_DSN: {{ .Values.db.dsn | b64enc | quote }}
  {{- end }}
  {{- if .Values.superUser.create }}
  CLOUD_SENTINEL_K8S_USERNAME: {{ .Values.superUser.username | b64enc | quote }}
  CLOUD_SENTINEL_K8S_PASSWORD: {{ .Values.superUser.password | b64enc | quote }}
  {{- end }}
{{- end }}